Repository initd1/HackAlert, pull requests merged in 2023-04, with the labels that each got.

#13 Error handling email module, code cleanup
  Common/utils.py
  IP/ip_reputation_checker.py
Labels: bug

#14 Bug/error handling email module
  .gitignore
  Config/config.ini
  Email/email_reputation_checker.py
Labels: bug

#17 Add error handling for Utils module
  Common/utils.py
Labels: bug

#10 Add username breach checker module
  Common/utils.py
  Username/__init__.py
  Username/username_reputation_checker.py
  main.py
  requirements.txt
Labels: enhancement

#18 fixed: bug in conditionals for argument options
  Email/email_reputation_checker.py
  all_breaches.json
  main.py
Labels: bug

#28 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#31 Bug/file-encoding-and-terminal-output-bug
  Common/utils.py
  Config/config.py
  Email/email_reputation_checker.py
  main.py
Labels: bug

#33 Docs/update readmemd with instructions on how to set up the test and execute tests
  README.md
Labels: documentation

#27 Docs/refactor project name
  Common/breach_checker.py
  Email/email_reputation_checker.py
  IP/ip_reputation_checker.py
  README.md
  Username/username_reputation_checker.py
  hackalert.py
Labels: documentation

#41 Bug/more-unicode-errors
  Tests/Config/test_config.py
  requirements.txt
Labels: bug

#46 Bug/error logging to terminal
  Common/breach_checker.py
  Common/utils.py
  Config/check_config_validity.py
  Config/config.py
  Config/formatter.py
  Email/email_reputation_checker.py
  IP/ip_reputation_checker.py
  Tests/Config/test_config.py
  Username/username_reputation_checker.py
  hackalert.py
  requirements.txt
Labels: bug

#55 update documentation
  .github/ISSUE_TEMPLATE/documentation.md
  CONTRIBUTION.md
  README.md
Labels: documentation

#61 Create docker-integrations.yml
  .github/workflows/docker-integrations.yml
Labels: documentation, ci/cd

#60 Update Docker-Integration to run only on merge to main. not on PR creation
  .github/workflows/docker-integrations.yml
  README.md
Labels: documentation

#63 Push Docker Image to Docker Hub when release is published
  .github/workflows/docker-integrations.yml
Labels: enhancement, ci/cd
